import { useState } from "react";
import { BaseEdge, EdgeLabelRenderer, getBezierPath, type EdgeProps } from "@xyflow/react";
import type { ConnectionRole, EtherEdge as SchemaEdge, PayloadChannel } from "@ether/schema";
import { CONNECTION_ROLES, PAYLOAD_CHANNELS, channelLabel, roleLabel } from "../ports/channelRegistry";

export type EtherFlowEdgeData = { edge: SchemaEdge; readOnly: boolean; compatibleSourceChannels: PayloadChannel[]; compatibleTargetChannels: PayloadChannel[]; onDelete(id: string): void; onRole(id: string, role: ConnectionRole): void; onChannel(id: string, endpoint: "source" | "target", channel: PayloadChannel): void; };
export function EtherEdge({ id, sourceX, sourceY, targetX, targetY, sourcePosition, targetPosition, markerEnd, selected, data }: EdgeProps & { data: EtherFlowEdgeData }) {
  const [rolesOpen, setRolesOpen] = useState(false); const [picker, setPicker] = useState<"source" | "target" | null>(null); const [rightDrag, setRightDrag] = useState<"source" | "target" | null>(null); const [dragTarget, setDragTarget] = useState<PayloadChannel | null>(null); const edge = data.edge; const [path, labelX, labelY] = getBezierPath({ sourceX, sourceY, sourcePosition, targetX, targetY, targetPosition }); const source = edge.from.channel; const target = edge.to.channel;
  const compatible = (endpoint: "source" | "target", channel: PayloadChannel) => (endpoint === "source" ? data.compatibleSourceChannels : data.compatibleTargetChannels).includes(channel);
  const chooseChannel = (endpoint: "source" | "target", channel: PayloadChannel) => { if (!data.readOnly && compatible(endpoint, channel)) data.onChannel(id, endpoint, channel); setPicker(null); setRightDrag(null); setDragTarget(null); };
  const openPicker = (endpoint: "source" | "target", dragging = false) => { if (!data.readOnly) { setRolesOpen(false); setPicker(endpoint); setRightDrag(dragging ? endpoint : null); } };
  return <><path d={path} fill="none" stroke="transparent" strokeWidth={18} className="ether-edge-hit-target" onContextMenu={(event) => { event.preventDefault(); event.stopPropagation(); if (!data.readOnly) data.onDelete(id); }} /><BaseEdge id={id} path={path} markerEnd={markerEnd} style={{ stroke: `var(--ether-channel-${source})`, strokeWidth: selected ? 3 : 2 }} />
    <EdgeLabelRenderer><div className={`ether-edge-label nodrag nopan${selected ? " is-selected" : ""}${edge.role !== "general" ? " is-named-role" : ""}`} style={{ transform: `translate(-50%, -50%) translate(${labelX}px, ${labelY}px)` }} data-testid="edge-role-chip" onContextMenu={(event) => { event.preventDefault(); event.stopPropagation(); if (!data.readOnly) data.onDelete(id); }}>
      <button type="button" disabled={data.readOnly} className={`ether-edge-channel-dot ether-edge-channel-${source}`} aria-label={`Source channel ${channelLabel(source)}`} onClick={() => openPicker("source")} onContextMenu={(event) => { event.preventDefault(); event.stopPropagation(); }} onPointerDown={(event) => { if (!data.readOnly && event.button === 2) { event.preventDefault(); openPicker("source", true); } }} />
      <button type="button" disabled={data.readOnly} className="ether-edge-role-chip" onClick={() => { if (!data.readOnly) { setPicker(null); setRolesOpen((value) => !value); } }}>{roleLabel(edge.role)}</button>
      <button type="button" disabled={data.readOnly} className={`ether-edge-channel-dot ether-edge-channel-${target}`} aria-label={`Target channel ${channelLabel(target)}`} onClick={() => openPicker("target")} onContextMenu={(event) => { event.preventDefault(); event.stopPropagation(); }} onPointerDown={(event) => { if (!data.readOnly && event.button === 2) { event.preventDefault(); openPicker("target", true); } }} />
      {rolesOpen ? <div className="ether-edge-role-grid" data-testid="edge-role-grid" role="menu">{CONNECTION_ROLES.map((role) => <button key={role} type="button" disabled={data.readOnly} aria-pressed={role === edge.role} onClick={() => { if (!data.readOnly) data.onRole(id, role); setRolesOpen(false); }}>{roleLabel(role)}</button>)}</div> : null}
      {picker ? <div className="ether-edge-channel-picker" role="menu" aria-label={`${picker === "source" ? "Source" : "Target"} compatible channels`} data-testid={`edge-channel-picker-${picker}`} onPointerLeave={() => setDragTarget(null)} onContextMenu={(event) => { event.preventDefault(); event.stopPropagation(); }}>{PAYLOAD_CHANNELS.map((channel) => { const allowed = compatible(picker, channel); return <button key={channel} type="button" disabled={data.readOnly || !allowed} aria-disabled={!allowed} className={`${rightDrag === picker && allowed ? "is-compatible-drag-target" : ""}${dragTarget === channel ? " is-drag-hover" : ""}`} title={allowed ? `Move endpoint to ${channelLabel(channel)}` : `${channelLabel(channel)} is unavailable for this endpoint`} onClick={() => chooseChannel(picker, channel)} onPointerEnter={() => { if (rightDrag === picker && allowed) setDragTarget(channel); }} onPointerUp={(event) => { if (!data.readOnly && event.button === 2 && rightDrag === picker && allowed) chooseChannel(picker, channel); }}><span className={`ether-edge-channel-dot ether-edge-channel-${channel}`} />{channelLabel(channel)}</button>; })}</div> : null}
    </div></EdgeLabelRenderer></>;
}
