import { BaseEdge, EdgeLabelRenderer, getBezierPath, type EdgeProps } from "@xyflow/react";
import type { ConnectionRole, EtherEdge as SchemaEdge, PayloadChannel } from "@ether/schema";
import { CONNECTION_ROLES, PAYLOAD_CHANNELS, channelLabel, roleLabel } from "../ports/channelRegistry";

export type EtherEdgeEditor = "role" | "source" | "target" | null;
export type EtherFlowEdgeData = { edge: SchemaEdge; editor: EtherEdgeEditor; readOnly: boolean; selected: boolean; compatibleSourceChannels: PayloadChannel[]; compatibleTargetChannels: PayloadChannel[]; onDelete(id: string): void; onRole(id: string, role: ConnectionRole): void; onChannel(id: string, endpoint: "source" | "target", channel: PayloadChannel): void; onEdit(id: string, editor: EtherEdgeEditor): void; onSelect(id: string): void; };
export function EtherEdge({ id, sourceX, sourceY, targetX, targetY, sourcePosition, targetPosition, markerEnd, data }: EdgeProps & { data: EtherFlowEdgeData }) {
  const edge = data.edge; const [path, labelX, labelY] = getBezierPath({ sourceX, sourceY, sourcePosition, targetX, targetY, targetPosition }); const source = edge.from.channel; const target = edge.to.channel;
  const rolesOpen = data.editor === "role"; const picker = data.editor === "source" || data.editor === "target" ? data.editor : null;
  const compatible = (endpoint: "source" | "target", channel: PayloadChannel) => (endpoint === "source" ? data.compatibleSourceChannels : data.compatibleTargetChannels).includes(channel);
  const chooseChannel = (endpoint: "source" | "target", channel: PayloadChannel) => { if (!data.readOnly && compatible(endpoint, channel)) data.onChannel(id, endpoint, channel); data.onEdit(id, null); };
  const openPicker = (endpoint: "source" | "target") => { if (!data.readOnly) data.onEdit(id, endpoint); };
  return <><path d={path} fill="none" stroke="transparent" strokeWidth={18} className="ether-edge-hit-target" onClick={(event) => { event.stopPropagation(); data.onSelect(id); }} onContextMenu={(event) => { event.preventDefault(); event.stopPropagation(); if (!data.readOnly) data.onDelete(id); }} /><BaseEdge id={id} path={path} markerEnd={markerEnd} style={{ stroke: `var(--ether-channel-${source})`, strokeWidth: data.selected ? 3 : 2 }} />
    <EdgeLabelRenderer><div className={`ether-edge-label nodrag nopan${data.selected ? " is-selected" : ""}${edge.role !== "general" ? " is-named-role" : ""}`} style={{ transform: `translate(-50%, -50%) translate(${labelX}px, ${labelY}px)` }} data-testid="edge-role-chip" onContextMenu={(event) => { event.preventDefault(); event.stopPropagation(); if (!data.readOnly) data.onDelete(id); }}>
      <button type="button" disabled={data.readOnly} className={`ether-edge-channel-dot ether-edge-channel-${source}`} aria-label={`Source channel ${channelLabel(source)}`} onPointerDown={(event) => event.stopPropagation()} onClick={(event) => { event.stopPropagation(); openPicker("source"); }} onContextMenu={(event) => { event.preventDefault(); event.stopPropagation(); if (!data.readOnly) data.onDelete(id); }} />
      <button type="button" disabled={data.readOnly} className={`ether-edge-role-chip${edge.role === "general" ? " is-general-role" : ""}`} onPointerDown={(event) => event.stopPropagation()} onClick={(event) => { event.stopPropagation(); if (!data.readOnly) data.onEdit(id, rolesOpen ? null : "role"); }}>{edge.role === "general" ? <><span className="sr-only">General</span><span aria-hidden="true">•</span></> : roleLabel(edge.role)}</button>
      <button type="button" disabled={data.readOnly} className={`ether-edge-channel-dot ether-edge-channel-${target}`} aria-label={`Target channel ${channelLabel(target)}`} onPointerDown={(event) => event.stopPropagation()} onClick={(event) => { event.stopPropagation(); openPicker("target"); }} onContextMenu={(event) => { event.preventDefault(); event.stopPropagation(); if (!data.readOnly) data.onDelete(id); }} />
      {rolesOpen ? <div className="ether-edge-role-grid" data-testid="edge-role-grid" role="menu" onPointerDown={(event) => event.stopPropagation()} onClick={(event) => event.stopPropagation()}>{CONNECTION_ROLES.map((role) => <button key={role} type="button" disabled={data.readOnly} aria-pressed={role === edge.role} onClick={() => { if (!data.readOnly) data.onRole(id, role); data.onEdit(id, null); }}>{roleLabel(role)}</button>)}</div> : null}
      {picker ? <div className="ether-edge-channel-picker" role="menu" aria-label={`${picker === "source" ? "Source" : "Target"} compatible channels`} data-testid={`edge-channel-picker-${picker}`} onContextMenu={(event) => { event.preventDefault(); event.stopPropagation(); }}>{PAYLOAD_CHANNELS.map((channel) => { const allowed = compatible(picker, channel); return <button key={channel} type="button" disabled={data.readOnly || !allowed} aria-disabled={!allowed} title={allowed ? `Move endpoint to ${channelLabel(channel)}` : `${channelLabel(channel)} is unavailable for this endpoint`} onClick={() => chooseChannel(picker, channel)}><span className={`ether-edge-channel-dot ether-edge-channel-${channel}`} />{channelLabel(channel)}</button>; })}</div> : null}
    </div></EdgeLabelRenderer></>;
}
