import { useCallback, useEffect, useState } from "react";
import { FolderSync, Power, RefreshCw, ShieldAlert } from "lucide-react";
import type { ApplicationCommand, LiveOutputSettings } from "@ether/schema";

export function LiveOutputPanel({ documentId, onStatus }: { documentId: string; onStatus(message: string): void }) {
  const [settings, setSettings] = useState<LiveOutputSettings | null>(null);
  const [destination, setDestination] = useState<{ grantId: string; displayName: string } | null>(null);
  const [namingPolicy, setNamingPolicy] = useState<"artifact" | "node" | "template">("artifact");
  const [collisionPolicy, setCollisionPolicy] = useState<"rename" | "skip" | "error">("rename");
  const [transferPolicy, setTransferPolicy] = useState<"copy" | "move">("copy");
  const [busy, setBusy] = useState(false);
  const refresh = useCallback(async () => { const response = await window.ether.application.query({ kind: "query", id: crypto.randomUUID(), correlationId: crypto.randomUUID(), documentId, name: "liveOutput.status", payload: {} }); if (response.name === "liveOutput.status") setSettings(response.payload.settings); }, [documentId]);
  useEffect(() => { void refresh(); }, [refresh]);
  useEffect(() => window.ether.application.onEvent((event) => { if ("documentId" in event && event.documentId === documentId && (event.name === "liveOutput.progress" || event.name === "liveOutput.attention")) void refresh(); }), [documentId, refresh]);
  const run = async (command: ApplicationCommand, message: string) => { setBusy(true); try { await window.ether.application.command(command); onStatus(message); await refresh(); } catch (cause) { onStatus(cause instanceof Error ? cause.message : "Live Output needs attention."); } finally { setBusy(false); } };
  const base = { kind: "command" as const, id: crypto.randomUUID(), correlationId: crypto.randomUUID(), documentId };
  const choose = async () => { const grant = await window.ether.permissions.grantFolder(documentId, "live-output"); if (grant) setDestination(grant); };
  return <section className="live-output-panel" aria-labelledby="live-output-title"><header><div><span className="eyebrow">Explicit mirror</span><h3 id="live-output-title"><FolderSync size={17} /> Live Output</h3></div><strong data-enabled={settings?.enabled ? "true" : "false"}>{settings?.enabled ? "Enabled" : "Disabled"}</strong></header><p>Disabled by default. Ether only mirrors future artifacts after you choose a destination and enable it.</p>
    {!settings?.enabled ? <div className="live-output-setup"><button type="button" onClick={() => void choose()}>{destination?.displayName ?? "Choose mirror folder…"}</button><div className="review-form-grid"><label>Naming<select value={namingPolicy} onChange={(event) => setNamingPolicy(event.target.value as typeof namingPolicy)}><option value="artifact">Artifact title</option><option value="node">Node title</option><option value="template">Stored template</option></select></label><label>Transfer<select value={transferPolicy} onChange={(event) => setTransferPolicy(event.target.value as typeof transferPolicy)}><option value="copy">Copy</option><option value="move">Move</option></select></label></div><label>Existing files<select value={collisionPolicy} onChange={(event) => setCollisionPolicy(event.target.value as typeof collisionPolicy)}><option value="rename">Rename safely</option><option value="skip">Skip</option><option value="error">Stop</option></select></label><button type="button" disabled={busy || !destination} onClick={() => void (destination && run({ ...base, name: "liveOutput.enable", payload: { pathGrantId: destination.grantId, namingPolicy, collisionPolicy, transferPolicy } }, "Live Output enabled."))}><Power size={14} />Enable Live Output</button></div>
    : <div className="live-output-actions"><p><ShieldAlert size={15} />Current mirror grant: <code>{settings.pathGrantId}</code></p><button type="button" disabled={busy} onClick={() => void run({ ...base, name: "liveOutput.reconcile", payload: {} }, "Live Output reconciled.")}><RefreshCw size={14} />Reconcile</button><button type="button" disabled={busy} onClick={() => void run({ ...base, name: "liveOutput.rebuild", payload: {} }, "Live Output rebuild started.")}>Rebuild mirror</button><button type="button" disabled={busy} onClick={() => void run({ ...base, name: "liveOutput.disable", payload: {} }, "Live Output disabled.")}>Disable</button><button type="button" className="danger" disabled={busy} onClick={() => void run({ ...base, name: "liveOutput.removeMirrorFiles", payload: { confirm: true } }, "Mirror cleanup started.")}>Remove mirror files</button></div>}
  </section>;
}
