import { randomUUID } from "node:crypto";
import { z } from "zod";

import { ApplicationCommandSchema, RecipeParameterValueSchema } from "@ether/schema";

import { activeDocumentId, applicationCommand, applicationQuery } from "../applicationAdapter.js";
import { EmptyInputSchema, NonEmptyIdSchema } from "../schemas.js";
import type { EtherToolDefinition } from "../toolTypes.js";
import { editAnnotations, readOnlyAnnotations } from "../toolTypes.js";

const recipeIdentity = {
  recipeId: NonEmptyIdSchema,
  version: NonEmptyIdSchema
};

export const recipeTools: EtherToolDefinition[] = [
  {
    name: "ether.recipe.list",
    description: "List installed executable Ether recipes and their versioned manifests.",
    inputSchema: EmptyInputSchema,
    annotations: readOnlyAnnotations,
    async run({ application }) {
      return applicationQuery(application, "recipe.catalog", {}, true);
    }
  },
  {
    name: "ether.recipe.setup",
    description: "Inspect the setup schema for one recipe version.",
    inputSchema: z.object(recipeIdentity).strict(),
    annotations: readOnlyAnnotations,
    async run({ application }, input) {
      return applicationQuery(application, "recipe.setupSchema", input, true);
    }
  },
  {
    name: "ether.recipe.preview",
    description: "Preview the atomic graph transaction generated by a recipe without inserting it.",
    inputSchema: z.object({ ...recipeIdentity, parameters: z.array(RecipeParameterValueSchema).default([]) }).strict(),
    annotations: readOnlyAnnotations,
    async run({ application }, input) {
      return applicationCommand(application, "recipe.preview", input);
    }
  },
  {
    name: "ether.recipe.instantiate",
    description: "Insert a recipe as one reversible graph transaction under an active Edit Permit. This never starts providers.",
    inputSchema: z.object({
      ...recipeIdentity,
      targetGraphId: NonEmptyIdSchema,
      parameters: z.array(RecipeParameterValueSchema).default([]),
      editPermitId: NonEmptyIdSchema
    }).strict(),
    annotations: editAnnotations,
    async run({ application }, input) {
      const { editPermitId: _editPermitId, ...payload } = input;
      const documentId = await activeDocumentId(application);
      const command = ApplicationCommandSchema.parse({
        kind: "command",
        id: `mcp-recipe-${randomUUID()}`,
        correlationId: `mcp-recipe-${randomUUID()}`,
        documentId,
        name: "recipe.instantiate",
        payload
      });
      return application.instantiateRecipe({ command, editPermitId: String(input.editPermitId) });
    }
  }
];
