export const testSuites = {
  unit: [
    "tests/acceptance-docs.test.ts",
    "tests/asset-drop.test.ts",
    "tests/brand-tokens.test.ts",
    "tests/canvas-history.test.ts",
    "tests/desktop-vite-config.test.ts",
    "tests/desktop-ipc-contract.test.ts",
    "tests/desktop-window-options.test.ts",
    "tests/document-operation-replay.test.ts",
    "tests/graph-kernel.test.ts",
    "tests/graph-assembly.test.ts",
    "tests/graph-catalog.test.ts",
    "tests/graph-channels.test.ts",
    "tests/graph-edge-semantics.test.ts",
    "tests/intelligence-context.test.ts",
    "tests/graph-taxonomy-25.test.ts",
    "tests/connection-matrix-4.0.test.ts",
    "tests/legacy-isolation-4.0.test.ts",
    "tests/plugin-4.0.test.ts",
    "tests/renderer-channel-registry.test.ts",
    "tests/renderer-url.test.ts",
    "tests/schema-4.0.test.ts"
  ],
  integration: [
    "tests/application-vertical-slice.test.ts",
    "tests/application-durability.test.ts",
    "tests/artifact-store.test.ts",
    "tests/assets.test.ts",
    "tests/desktop-settings-store.test.ts",
    "tests/document-format.test.ts",
    "tests/document-blobs.test.ts",
    "tests/document-graph-repository.test.ts",
    "tests/document-locking.test.ts",
    "tests/document-recovery.test.ts",
    "tests/desktop/document-lifecycle.spec.ts",
    "tests/execution-engine.test.ts",
    "tests/job-coordinator.test.ts",
    "tests/migration.test.ts",
    "tests/project-store.test.ts",
    "tests/codex-app-server-client.test.ts",
    "tests/codex-app-server-provider.test.ts",
    "tests/antigravity-provider.test.ts",
    "tests/provider-capability-probe.test.ts",
    "tests/provider-lifecycle.test.ts",
    "tests/provider-registry.test.ts",
    "tests/recipe-catalog.test.ts",
    "tests/recipe-instantiation.test.ts",
    "tests/recipe-acceptance.test.ts",
    "tests/recipe-application.test.ts",
    "tests/execution-plan.test.ts",
    "tests/export-codec.test.ts",
    "tests/batch-scheduler.test.ts",
    "tests/application-contract-4.0.test.ts",
    "tests/live-output.test.ts",
    "tests/mcp-4.0.test.ts",
    "tests/durable-repositories.test.ts",
    "tests/revision-store.test.ts",
    "tests/vision-evaluation.test.ts",
    "tests/windows-package.test.ts"
  ],
  contracts: [
    "tests/api-provider-infrastructure.test.ts",
    "tests/asset-ipc-validation.test.ts",
    "tests/codex-plugin.test.ts",
    "tests/mcp-2.0.test.ts",
    "tests/mcp-server.test.ts",
    "tests/preload-file-path.test.ts",
    "tests/provider-contract.test.ts",
    "tests/workspace-command-surface.test.ts"
  ],
  performance: ["tests/prompt-assembly.performance.test.ts"],
  "conformance:codex": [
    "tests/codex.conformance.test.ts",
    "tests/conformance/codex-live.conformance.ts"
  ],
  "conformance:antigravity": ["tests/antigravity.conformance.test.ts", "tests/conformance/antigravity-live.conformance.ts"],
  smoke: [
    "tests/smoke.spec.ts",
    "tests/desktop/shell-layout.spec.ts",
    "tests/desktop/canvas.spec.ts",
    "tests/desktop/recipe-gallery.spec.ts",
    "tests/desktop/inspectors.spec.ts",
    "tests/desktop/references-batches-runs.spec.ts",
    "tests/desktop/artifacts-review.spec.ts",
    "tests/desktop/drawing-edit.spec.ts"
  ],
  desktop: ["tests/desktop/document-lifecycle.electron.spec.ts"],
  packaged: ["tests/desktop/document-lifecycle.packaged.ts"]
} as const;
