export const testSuites = {
  unit: [
    "tests/acceptance-docs.test.ts",
    "tests/asset-drop.test.ts",
    "tests/canvas-reference-drop.test.ts",
    "tests/brand-tokens.test.ts",
    "tests/canvas-authoring-commands.test.ts",
    "tests/module-authoring.test.ts",
    "tests/canvas-history.test.ts",
    "tests/desktop-vite-config.test.ts",
    "tests/desktop-ipc-contract.test.ts",
    "tests/desktop-window-options.test.ts",
    "tests/document-operation-replay.test.ts",
    "tests/document-shortcuts.test.ts",
    "tests/graph-kernel.test.ts",
    "tests/gemini-live-conformance-contract.test.ts",
    "tests/intelligence-context.test.ts",
    "tests/manual-4.0.test.ts",
    "tests/connection-matrix-4.0.test.ts",
    "tests/no-legacy-4.0.test.ts",
    "tests/plugin-4.0.test.ts",
    "tests/renderer-channel-registry.test.ts",
    "tests/artifact-export-ux.test.ts",
    "tests/recovery-journey-driver.test.ts",
    "tests/recovery-worker-simulation.test.ts",
    "tests/renderer-url.test.ts",
    "tests/reference-preview.test.ts",
    "tests/reference-asset.test.ts",
    "tests/schema-4.0.test.ts",
    "tests/windows-integration-contract.test.ts"
  ],
  integration: [
    "tests/application-vertical-slice.test.ts",
    "tests/application-durability.test.ts",
    "tests/desktop-settings-store.test.ts",
    "tests/document-format.test.ts",
    "tests/document-blobs.test.ts",
    "tests/document-graph-repository.test.ts",
    "tests/document-locking.test.ts",
    "tests/document-recovery.test.ts",
    "tests/security-boundaries.test.ts",
    "tests/error-observability.test.ts",
    "tests/network-egress.test.ts",
    "tests/desktop/document-lifecycle.spec.ts",
    "tests/codex-app-server-client.test.ts",
    "tests/codex-app-server-provider.test.ts",
    "tests/antigravity-provider.test.ts",
    "tests/gemini-image-provider.test.ts",
    "tests/gemini-credential-store.test.ts",
    "tests/provider-capability-probe.test.ts",
    "tests/provider-lifecycle.test.ts",
    "tests/provider-registry.test.ts",
    "tests/recipe-catalog.test.ts",
    "tests/recipe-instantiation.test.ts",
    "tests/recipe-acceptance.test.ts",
    "tests/recipe-application.test.ts",
    "tests/execution-plan.test.ts",
    "tests/filter-route-executors.test.ts",
    "tests/filter-route-persistence.test.ts",
    "tests/variables-join.test.ts",
    "tests/export-codec.test.ts",
    "tests/batch-scheduler.test.ts",
    "tests/application-contract-4.0.test.ts",
    "tests/t19-application.test.ts",
    "tests/t21-application.test.ts",
    "tests/local-media-runtime.test.ts",
    "tests/review-runtime.test.ts",
    "tests/local-output-publication.test.ts",
    "tests/live-output.test.ts",
    "tests/mcp-4.0.test.ts",
    "tests/durable-repositories.test.ts",
    "tests/windows-package.test.ts",
    "tests/document-compatibility-4x.test.ts"
  ],
  "destructive-chaos": ["tests/document-chaos.integration.ts"],
  contracts: [
    "tests/api-provider-infrastructure.test.ts",
    "tests/asset-ipc-validation.test.ts",
    "tests/preload-file-path.test.ts",
    "tests/provider-contract.test.ts",
    "tests/workspace-command-surface.test.ts"
  ],
  performance: [
    "tests/performance/document-open.performance.ts",
    "tests/performance/canvas.performance.ts",
    "tests/performance/artifact-search.performance.ts",
    "tests/performance/artifact-asset.performance.ts",
    "tests/performance/large-sparse-asset.performance.ts",
    "tests/performance/provider-dispatch.performance.ts",
    "tests/document-page-size.performance.ts"
  ],
  performanceBrowser: [
    "tests/performance/canvas.browser.performance.spec.ts",
    "tests/performance/desktop.production.performance.spec.ts"
  ],
  "conformance:codex": [
    "tests/codex.conformance.test.ts",
    "tests/conformance/codex-live.conformance.ts"
  ],
  "conformance:antigravity": ["tests/antigravity.conformance.test.ts", "tests/conformance/antigravity-live.conformance.ts"],
  smoke: [
    "tests/smoke.spec.ts",
    "tests/desktop/shell-layout.spec.ts",
    "tests/desktop/release-status.spec.ts",
    "tests/desktop/gemini-credential-setup.spec.ts",
    "tests/desktop/canvas.spec.ts",
    "tests/desktop/canvas-reference-drop.spec.ts",
    "tests/desktop/recipe-gallery.spec.ts",
    "tests/desktop/document-history.spec.ts",
    "tests/desktop/inspectors.spec.ts",
    "tests/desktop/references-batches-runs.spec.ts",
    "tests/desktop/artifacts-review.spec.ts",
    "tests/desktop/drawing-edit.spec.ts"
  ],
  recoveryBaseline: ["tests/recovery/authoring-baseline.spec.ts"],
  recoveryJ02NodeCatalog: ["tests/recovery/j02-node-catalog.spec.ts"],
  recoveryGuiCheckpoint: ["tests/recovery/gui-checkpoint.spec.ts"],
  recoveryModuleAuthoring: ["tests/recovery/module-authoring-recovery.spec.ts"],
  recoveryConnectionInspector: ["tests/recovery/connection-inspector-recovery.spec.ts"],
  recoveryT13RunSafety: ["tests/recovery/t13-run-safety-packaged.spec.ts"],
  recoveryT14WorkerReview: ["tests/recovery/t14-worker-review-packaged.spec.ts"],
  recoveryT15ReferenceSet: ["tests/recovery/t15-reference-set-packaged.spec.ts"],
  recoveryT16T19Visible: ["tests/recovery/t16-t19-visible-packaged.spec.ts"],
  recoveryT20Recipes: ["tests/recovery/t20-recipes-packaged.spec.ts"],
  recoveryT21PluginCoproduction: ["tests/recovery/t21-plugin-coproduction-packaged.spec.ts"],
  recoveryT22ShellMatrix: ["tests/recovery/t22-packaged-shell-matrix.spec.ts"],
  recoveryT23Keyboard: [
    "tests/recovery/t23-keyboard-packaged.spec.ts",
    "tests/recovery/t23-j06-keyboard-packaged.spec.ts"
  ],
  recoveryManual: ["tests/recovery/manual-recovery.spec.ts"],
  recoveryDocumentLifecycle: ["tests/recovery/document-lifecycle-recovery.spec.ts"],
  recoveryVisiblePackaged: ["tests/recovery/visible-recovery-packaged.spec.ts"],
  recoveryWindowsIntegration: ["tests/recovery/document-windows-integration.spec.ts"],
  desktop: ["tests/desktop/document-lifecycle.electron.spec.ts"],
  packaged: ["tests/desktop/document-lifecycle.packaged.ts", "tests/packaged-electron.packaged.ts"]
} as const;
